config:
  test:
    message: This is message for bot-service [CHANGED].

logging:
  level:
    root: info
    
---
# this is a development profile
# use it for local development and testing
spring:
  profiles: development
  datasource:
    sql-script-encoding: UTF-8
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: false
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false

application:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5434/bots-db
    username: postgres
    password: postgres

---
# this is a production profile
spring:
  profiles: production
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false