config:
  test:
    message: Spring Cloud Config provides server and client-side support for externalized configuration in a distributed system. With the Config Server you have a central place to manage external properties for applications across all environments.

logging:
  level:
    root: info

spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
    
---
# this is a development profile
# use it for local development and testing
spring:
  profiles: development
  datasource:
    sql-script-encoding: UTF-8
    platform: h2
    type: org.apache.tomcat.jdbc.pool.DataSource
  jpa:
    hibernate.ddl-auto: create
    show-sql: false
  h2.console.enabled: true
  h2.console.path: /h2-console
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false

application:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:application;DB_CLOSE_DELAY=1000
    username: sa
    password:

---
# this is a production profile
spring:
  profiles: production
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false